### ISSUE TITLE
import not working

### ISSUE THREAD

**Issue by Groblockia** [Ryhon0/GodotLidar#1]
i downloaded and extracted the source code, and when i try opening it in godot, at startup i get these errors messages: ![image](https://user-images.githubusercontent.com/106343715/183767334-f487e4a4-f25b-4c72-bf50-1f1e9c02298a.png)
 and when i launch the game i get these: 
![image](https://user-images.githubusercontent.com/106343715/183767456-5b6990e7-77a4-49b6-9fc1-7e063fc02d68.png)
and in my file explorer, i can clearly see the .cs files actually exists, but in the godot file explorer they don't exist
![image](https://user-images.githubusercontent.com/106343715/183767667-945a58c3-6388-43af-b631-1a4bf76b9671.png)
![image](https://user-images.githubusercontent.com/106343715/183767698-c1b71766-9983-4792-97e2-7f2969dbe8ef.png)

**Comment by Ryhon0** [comment]
You are using a Godot version without Mono support

**Comment by Matgriv** [comment]
oh yeah i'm dumb, i tought the same version could support the 2 languages, srry
